# Generated by Django 4.1.7 on 2023-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
