# Generated by Django 4.1.7 on 2023-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprj', '0003_alter_category_options_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
